export const SET_TEST = 'SET_TEST';
export const SET_BREADREUMB = "SET_BREADREUMB";
export const SET_NAVID = "SET_NAVID";
export const SET_MENUDATA = "SET_MENUDATA";
export const LOADING_FUNC = "LOADING_FUNC";
export const CHANGE_HOME_MODULE = "CHANGE_HOME_MODULE";
export const SET_LOCAL_DEVICE_INFO = "SET_LOCAL_DEVICE_INFO"; //本地设备信息设置
export const CHANGE_IP = "CHANGE_IP";
export const CHANGE_BSTU = "CHANGE_BSTU";
export const ALERT_FUNC = "ALERT_FUNC";
export const GET_ALL_MODULE = "GET_ALL_MODULE";
export const TOP_OBJ = "TOP_OBJ";
export const CHANGE_TOPO = "CHANGE_TOPO";
export const CHANGE_TOPO_IMAGE = "CHANGE_TOPO_IMAGE"; //拓扑状态图片
export const TOPO_IMAGE_HAS_CHANGE = "TOPO_IMAGE_HAS_CHANGE"; //拓扑状态图片变化标记
export const SET_PAGEDATA = "SET_PAGEDATA";
export const SET_IPDATA = "SET_IPDATA";
export const SET_IPCHECKEDSTU = "SET_IPCHECKEDSTU"
